function fontFunction1()
{
  document.getElementById("f1").style.fontSize="small";
  document.getElementById("f2").style.fontSize="small";
  document.getElementById("f3").style.fontSize="small";
  document.getElementById("f4").style.fontSize="small";
  document.getElementById("f5").style.fontSize="small";
  document.getElementById("f6").style.fontSize="small";
  document.getElementById("f7").style.fontSize="small";
  document.getElementById("f8").style.fontSize="small";
  document.getElementById("f9").style.fontSize="small";
  document.getElementById("f10").style.fontSize="small";
  document.getElementById("f11").style.fontSize="small";
  document.getElementById("f12").style.fontSize="small";  
  document.getElementById("f13").style.fontSize="small";  
  document.getElementById("f14").style.fontSize="small";
  document.getElementById("f15").style.fontSize="small";
  document.getElementById("f16").style.fontSize="small";
}
function fontFunction2()
{
  document.getElementById("f1").style.fontSize="large";
  document.getElementById("f2").style.fontSize="large";
  document.getElementById("f3").style.fontSize="large";
  document.getElementById("f4").style.fontSize="large";
  document.getElementById("f5").style.fontSize="large";
  document.getElementById("f6").style.fontSize="large";
  document.getElementById("f7").style.fontSize="large";
  document.getElementById("f8").style.fontSize="large";
  document.getElementById("f9").style.fontSize="large";
  document.getElementById("f10").style.fontSize="large";
  document.getElementById("f11").style.fontSize="large";
  document.getElementById("f12").style.fontSize="large";
  document.getElementById("f13").style.fontSize="large";
  document.getElementById("f14").style.fontSize="large";
  document.getElementById("f15").style.fontSize="large";
  document.getElementById("f16").style.fontSize="large";
}
function fontFunction3()
{
  document.getElementById("f1").style.fontSize="20px";
  document.getElementById("f2").style.fontSize="20px";
  document.getElementById("f3").style.fontSize="20px"; 
  document.getElementById("f4").style.fontSize="20px";
  document.getElementById("f5").style.fontSize="20px";
  document.getElementById("f6").style.fontSize="20px";
  document.getElementById("f7").style.fontSize="20px";
  document.getElementById("f8").style.fontSize="20px";
  document.getElementById("f9").style.fontSize="20px";
  document.getElementById("f10").style.fontSize="20px";
  document.getElementById("f11").style.fontSize="20px";
  document.getElementById("f12").style.fontSize="20px";
  document.getElementById("f13").style.fontSize="20px";
  document.getElementById("f14").style.fontSize="20px";
  document.getElementById("f15").style.fontSize="20px";
  document.getElementById("f16").style.fontSize="20px";
}

